services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - /home/pi/docker/influxdb/data:/var/lib/influxdb:rw
      - /home/pi/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - 8086:8086
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

    labels:
      - diun.enable=true      