version: '3.8'
services:
  # add the mariadb service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - "/home/pi/docker/mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: password
  
  # Optional GUI for mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8020:8080

# To use the CLI to access mariadb directly execute the following:
# docker exec -it mariadb mysql --user=root --password=password

# Login details for the mariadb GUI localhost:8020:
# Server = name of the mariadb container. "mariadb" in my case.
# Username = root
# Password = password (same as the password mentioned above)